"""
ChronosMatch IPC Consumer.

Reads orders from the mmap ring buffer, processes them through
the Cython matching engine, publishes matched trades to a trade
mmap ring buffer, and asynchronously persists those trades to SQLite.

Week 4 additions:
- Asynchronous trade persistence
- Durable SQLite audit ledger
- Whale-order detection for the terminal demonstration
"""

import os
import time

from ipc import RingBuffer, BUY
from ipc.trade_ring_buffer import TradeRingBuffer
from ipc.trade_protocol import Trade

from cython_engine.matching_engine import CythonMatchingEngine

from persistence.trade_ledger import TradeLedger
from persistence.trade_flusher import TradeFlusher


# ============================================================
# CONFIGURATION
# ============================================================

IPC_FILE = "e2e_chronosmatch.ipc"
BUFFER_CAPACITY = 100_000

TRADE_IPC_FILE = "chronosmatch.trades.ipc"
TRADE_BUFFER_CAPACITY = 10_000

TRADE_DATABASE = "chronosmatch.db"

# An order is considered a "whale" when its quantity reaches
# this threshold AND the order clears at least two price levels.
WHALE_QUANTITY_THRESHOLD = 5_000


# ============================================================
# WEEK 4 WHALE DETECTION
# ============================================================

def analyze_whale_order(order, trades):
    """
    Analyze one order and the trades generated by that order.

    Returns:
        tuple:
            is_whale        -> True/False
            levels_cleared  -> number of distinct trade prices
            matched_quantity -> total quantity matched

    The function is intentionally independent of the matching
    engine so the terminal Whale demo can use it directly.
    """

    if not trades:
        return False, 0, 0

    prices = set()
    matched_quantity = 0

    for trade in trades:
        if "price" in trade:
            prices.add(trade["price"])

        matched_quantity += int(
            trade.get("quantity", 0)
        )

    levels_cleared = len(prices)

    is_whale = (
        int(order.quantity) >= WHALE_QUANTITY_THRESHOLD
        and levels_cleared >= 2
    )

    return (
        is_whale,
        levels_cleared,
        matched_quantity,
    )


# ============================================================
# ORDER CONSUMER
# ============================================================

class OrderConsumer:
    """Consumes orders and asynchronously persists matched trades."""

    def __init__(
        self,
        ipc_file: str = IPC_FILE,
        buffer_capacity: int = BUFFER_CAPACITY,
        trade_ipc_file: str = TRADE_IPC_FILE,
        trade_buffer_capacity: int = TRADE_BUFFER_CAPACITY,
        trade_database: str = TRADE_DATABASE,
    ):
        self.ipc_file = ipc_file
        self.buffer_capacity = buffer_capacity

        self.trade_ipc_file = trade_ipc_file
        self.trade_buffer_capacity = trade_buffer_capacity
        self.trade_database = trade_database

        # Order IPC ring buffer.
        self.ring_buffer = RingBuffer(
            path=self.ipc_file,
            capacity=self.buffer_capacity,
        )

        # Cython matching engine.
        self.engine = CythonMatchingEngine()

        # Matched-trade IPC ring buffer.
        self.trade_buffer = TradeRingBuffer(
            path=self.trade_ipc_file,
            capacity=self.trade_buffer_capacity,
        )

        # SQLite ledger. The actual connection is opened by
        # TradeFlusher inside its worker thread.
        self.trade_ledger = TradeLedger(
            database_path=self.trade_database,
        )

        # Background persistence worker.
        self.trade_flusher = TradeFlusher(
            trade_buffer=self.trade_buffer,
            ledger=self.trade_ledger,
            batch_size=100,
            poll_interval=0.001,
        )

        # Runtime counters.
        self.orders_consumed = 0
        self.trades_generated = 0
        self.trades_published = 0
        self.next_trade_id = 1

        self.start_time = None
        self.expected_orders = 0

    # --------------------------------------------------------
    # CONNECTION
    # --------------------------------------------------------

    def connect(self):
        """Open the order IPC buffer and start trade persistence."""

        if not os.path.exists(self.ipc_file):
            raise FileNotFoundError(
                f"IPC file not found: {self.ipc_file}\n"
                "Start the market producer first."
            )

        self.ring_buffer.open()

        self.expected_orders = (
            self.ring_buffer.get_expected_orders()
        )

        # The trade IPC file is created fresh for this run.
        if os.path.exists(self.trade_ipc_file):
            try:
                os.remove(self.trade_ipc_file)
            except PermissionError as error:
                raise RuntimeError(
                    "Trade IPC file is currently in use: "
                    f"{self.trade_ipc_file}"
                ) from error

        self.trade_buffer.create()

        # Important:
        # TradeFlusher opens SQLite inside its own worker thread.
        self.trade_flusher.start()

        print("=" * 65)
        print("ChronosMatch Week 4 Consumer")
        print("=" * 65)
        print(
            f"Expected orders     : "
            f"{self.expected_orders:,}"
        )
        print("Cython engine       : ENABLED")
        print("Trade mmap          : ENABLED")
        print("Async SQLite        : ENABLED")
        print("Background flusher  : RUNNING")
        print(
            f"Whale threshold     : "
            f"{WHALE_QUANTITY_THRESHOLD:,}"
        )
        print()
        print("Waiting for orders...\n")

    # --------------------------------------------------------
    # ORDER PROCESSING
    # --------------------------------------------------------

    def process_order(self, order):
        """Match one order and publish all generated trades."""

        is_buy = order.side == BUY

        # Keep the existing Cython matching API unchanged.
        trades = self.engine.match_order(
            order.order_id,
            order.price,
            order.quantity,
            is_buy,
            order.timestamp_ns,
        )

        # ----------------------------------------------------
        # WHALE DETECTION (Python-side, after Cython matching)
        # ----------------------------------------------------
        # Only inspect large orders. This keeps the normal path
        # lightweight while leaving the Cython hot path unchanged.
        if int(order.quantity) >= WHALE_QUANTITY_THRESHOLD and trades:
            (
                is_whale,
                levels_cleared,
                matched_quantity,
            ) = analyze_whale_order(order, trades)

            if is_whale:
                self.display_whale_alert(
                    order,
                    levels_cleared,
                    matched_quantity,
                )

        # Convert Cython/Python trade dictionaries into the
        # fixed-size Trade representation used by the trade mmap.
        for trade_data in trades:
            trade = Trade(
                trade_id=self.next_trade_id,
                buy_order_id=trade_data["buy_order_id"],
                sell_order_id=trade_data["sell_order_id"],
                price=trade_data["price"],
                quantity=trade_data["quantity"],
                timestamp_ns=time.perf_counter_ns(),
            )

            # Back-pressure if the trade ring buffer is full.
            while not self.trade_buffer.write(trade):
                time.sleep(0.0001)

            self.next_trade_id += 1
            self.trades_published += 1

        self.orders_consumed += 1
        self.trades_generated += len(trades)

        return trades

    # --------------------------------------------------------
    # WHALE TERMINAL UI
    # --------------------------------------------------------

    def display_whale_alert(
        self,
        order,
        levels_cleared,
        matched_quantity,
    ):
        """Display a clear terminal alert for a detected whale order."""

        side = (
            "BUY"
            if order.side == BUY
            else "SELL"
        )

        print()
        print("!" * 65)
        print("               🐋 WHALE ORDER DETECTED")
        print("!" * 65)
        print(
            f"Order ID           : {order.order_id:,}"
        )
        print(
            f"Side               : {side}"
        )
        print(
            f"Order quantity     : {order.quantity:,}"
        )
        print(
            f"Matched quantity   : {matched_quantity:,}"
        )
        print(
            f"Price              : {order.price:.2f}"
        )
        print(
            f"Levels cleared     : {levels_cleared}"
        )
        print(
            f"Threshold          : {WHALE_QUANTITY_THRESHOLD:,}"
        )
        print("!" * 65)
        print()

    # --------------------------------------------------------
    # CONSUMER LOOP
    # --------------------------------------------------------

    def consume(self):
        """
        Consume orders until the producer has finished and all
        expected orders have been processed.
        """

        self.start_time = time.perf_counter()
        last_display = self.start_time

        while True:
            order = self.ring_buffer.read()

            if order is not None:
                trades = self.process_order(order)

                # Print only the first ten orders to avoid flooding
                # the terminal during a large benchmark.
                if self.orders_consumed <= 10:
                    side = (
                        "BUY"
                        if order.side == BUY
                        else "SELL"
                    )

                    print(
                        f"Order ID={order.order_id:<6} "
                        f"Side={side:<4} "
                        f"Price={order.price:>8.2f} "
                        f"Qty={order.quantity:<5} "
                        f"Trades={len(trades)}"
                    )

            else:
                # Stop only after:
                # 1. Producer says it is finished.
                # 2. Every expected order has been consumed.
                if (
                    self.ring_buffer.is_producer_done()
                    and self.orders_consumed >= self.expected_orders
                ):
                    break

                time.sleep(0)

            current_time = time.perf_counter()

            if current_time - last_display >= 1:
                self.display_statistics(current_time)
                last_display = current_time

    # --------------------------------------------------------
    # LIVE STATISTICS
    # --------------------------------------------------------

    def display_statistics(self, current_time):
        """Display live consumer and persistence statistics."""

        elapsed = current_time - self.start_time

        rate = (
            self.orders_consumed / elapsed
            if elapsed > 0
            else 0
        )

        print(
            f"[Consumer] "
            f"Orders: {self.orders_consumed:,} | "
            f"Rate: {rate:,.0f} orders/sec | "
            f"Trades: {self.trades_generated:,} | "
            f"Published: {self.trades_published:,} | "
            f"Persisted: "
            f"{self.trade_flusher.trades_flushed:,}"
        )

    # --------------------------------------------------------
    # FINAL STATISTICS
    # --------------------------------------------------------

    def print_final_statistics(self):
        """Display final statistics after the flusher has drained."""

        if self.start_time is None:
            return

        elapsed = (
            time.perf_counter()
            - self.start_time
        )

        rate = (
            self.orders_consumed / elapsed
            if elapsed > 0
            else 0
        )

        print()
        print("=" * 65)
        print("ChronosMatch Week 4 Consumer Finished")
        print("=" * 65)

        print(
            f"Expected orders     : "
            f"{self.expected_orders:,}"
        )

        print(
            f"Orders consumed     : "
            f"{self.orders_consumed:,}"
        )

        print(
            f"Orders missing      : "
            f"{self.expected_orders - self.orders_consumed:,}"
        )

        print(
            f"Elapsed time        : "
            f"{elapsed:.6f} sec"
        )

        print(
            f"Throughput          : "
            f"{rate:,.2f} orders/sec"
        )

        print(
            f"Trades generated    : "
            f"{self.trades_generated:,}"
        )

        print(
            f"Trades published    : "
            f"{self.trades_published:,}"
        )

        print(
            f"Trades persisted    : "
            f"{self.trade_flusher.trades_flushed:,}"
        )

        print(
            f"Buy orders left     : "
            f"{self.engine.get_buy_order_count():,}"
        )

        print(
            f"Sell orders left    : "
            f"{self.engine.get_sell_order_count():,}"
        )

        print(
            f"Flusher error       : "
            f"{self.trade_flusher.error}"
        )

        print("=" * 65)

    # --------------------------------------------------------
    # CLEANUP
    # --------------------------------------------------------

    def close(self):
        """
        Gracefully stop the persistence worker and close IPC
        resources.

        The flusher is stopped FIRST so its worker thread can
        perform its final drain and close its SQLite connection
        safely in the same thread that opened it.
        """

        self.trade_flusher.stop()

        self.trade_buffer.close()

        self.ring_buffer.close()


# ============================================================
# MAIN
# ============================================================

def main():
    consumer = OrderConsumer()

    try:
        consumer.connect()
        consumer.consume()

    except KeyboardInterrupt:
        print("\nConsumer stopped by user.")

    except FileNotFoundError as error:
        print(f"\nERROR: {error}")

    except RuntimeError as error:
        print(f"\nERROR: {error}")

    finally:
        # Always stop the flusher before closing the trade mmap.
        consumer.close()

        # Print only after the worker has completely finished.
        consumer.print_final_statistics()


if __name__ == "__main__":
    main()
